name: coingecko_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/pangz-lab/coingecko_client
license: BSD 3-Clause

environment:
  sdk: '>=2.19.3 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  http: ^0.13.5