name: coingecko_client_unit_test

on:
  push:
    branches:
      - 'master'
      - 'feature/**'
      - 'release/**'
  pull_request:
    branches:
      - 'master'
      - 'feature/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [2.19.3, stable, beta, dev]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }
      
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Run unit tests
        run: dart test --coverage=./test_coverage test/domain

      - name: Push result to Testspace server
        run: |
          testspace ./test_coverage/**/*.json coverage.xml
        if: always()
