name: coingecko_client_integration_test

on:
  push:
    branches:
      - 'master'
      - 'feature/**'
  pull_request:
    branches:
      - 'master'
      - 'feature/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [2.19.3, stable, beta, dev]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Run integration tests
        run: dart test test/coingecko_real_request_test.dart